### ISSUE TITLE
Keep measurements as numbers

### ISSUE THREAD

**Issue by ecumene** [Hello-World-Software-Studios/calculator#14]
https://github.com/Hello-World-Software-Studios/calculator/blob/9613c5b28b4e142fc053225d82b785d43e3989e1/src/components/calculator.jsx#L30

Replace with something like
```
[1, 2, 3].join(", "); // "1, 2, 3"
```
on https://github.com/Hello-World-Software-Studios/calculator/blob/9613c5b28b4e142fc053225d82b785d43e3989e1/src/components/calculator.jsx#L110

**Comment by JPM709** [comment]
used  built-in join function to replace my manual joining in makeAList(). now ", " appears only once instead of multiple times
