### ISSUE TITLE
Add brackets around else

### ISSUE THREAD

**Issue by ecumene** [Hello-World-Software-Studios/calculator#23]
https://github.com/Hello-World-Software-Studios/calculator/blob/c4bec9890d695b722df2186732f6c1e14ee283cb/src/components/calculator.jsx#L16
```
if (i === 1) {
    newArray.push(onCenterSpacing-studOffset);
} else {
    newArray.push((i*onCenterSpacing)-studOffset);
}
```

**Comment by JPM709** [comment]
I added the brackets, but should the else go up on the same line as the if's closing brace?

**Comment by ecumene** [comment]
Hmm, could you write out what you mean?

**Comment by JPM709** [comment]
`if (i === 1) {
    newArray.push(onCenterSpacing-studOffset);
} 
else {
    newArray.push((i*onCenterSpacing)-studOffset);
}`

just placing my else expression on a new line, so the closing braces are by themselves.

**Comment by JPM709** [comment]
I found a way to simplify this function anyway, so that else is no longer needed. But I'd still like to know

**Comment by JPM709** [comment]
Since we discussed the standard formatting for this issue, Im going to mark this as closed.
