### ISSUE TITLE
Move make a list out for a cleaner flow

### ISSUE THREAD

**Issue by ecumene** [Hello-World-Software-Studios/calculator#25]
https://github.com/Hello-World-Software-Studios/calculator/blob/c4bec9890d695b722df2186732f6c1e14ee283cb/src/components/calculator.jsx#L13

Move this out of your component (put it in the lines above your component) and make all its parameters inputs to the function (isImperialUnit, onCenterSpacing...)

**Comment by JPM709** [comment]
moved makeAList to top level, and now when I call it, I feed it parameters. 

function layoutWall() {
        setListOfMeasurements(makeAList(wallLength, onCenterSpacing, studOffset, isImperialUnit));
    }
