### ISSUE TITLE
Move state out of calculator and into project manager

### ISSUE THREAD

**Issue by ecumene** [Hello-World-Software-Studios/calculator#33]

**Comment by JPM709** [comment]
mostly done. still buggy but works. Ill close the issue once I'm sure it works 100%

**Comment by ecumene** [comment]
Let's try moving list of measurements from the back end to the front end so we don't have to fetch it which simplifies this:

1. Delete the studs table
2. Change the walls table to have a `wallLength`, which determines the actual length of the wall. This should be stored as metric in the database and converted if needed on the front end.
3. Include the walls in your `GET /projects/{id}`

**Comment by JPM709** [comment]
state has been successfully lifted up to parent. had a problem with the callback I passed down. 
next task is to move it to front end

**Comment by JPM709** [comment]
calculating the list is done on the front end now, working as expected.
