### ISSUE TITLE
Goal: Make a post to add a project

### ISSUE THREAD

**Issue by ecumene** [Hello-World-Software-Studios/calculator#40]

**Comment by ecumene** [comment]
Nice work! Just need to return the Project ID and such via `INSERT ... RETURNING ...`

**Comment by ecumene** [comment]
https://www.postgresql.org/docs/9.5/dml-returning.html

**Comment by JPM709** [comment]
Can create a user that returns a unique user ID from SQL. That ID is then used when a project is created as owner_user_id. The created project then returns a project_id, which is used when a wall is added to the project. Tested a couple times last night, appears to be working correctly. I'm very happy about this
