### ISSUE TITLE
Remove template string

### ISSUE THREAD

**Issue by ecumene** [Hello-World-Software-Studios/calculator#44]
```
-        {`Current Project: ${displayProjectName}`}
+        Current Project:
+        {displayProjectName}
```

**Comment by ecumene** [comment]
Look into HTML Escaping for this as well

https://stackoverflow.com/questions/7381974/which-characters-need-to-be-escaped-in-html

**Comment by JPM709** [comment]
removed all template strings in html text fields, used &nbsp; to fix spacing issues.
