### ISSUE TITLE
`reuseableCode.js` -> `constants.js`

### ISSUE THREAD

**Issue by ecumene** [Hello-World-Software-Studios/calculator#55]

**Comment by JPM709** [comment]
`const NO_NAME_TO_DISPLAY = "Nothing To Display";

export default NO_NAME_TO_DISPLAY;` in one file.

`import NO_NAME_TO_DISPLAY from "./constants";

const checkForNameToDisplay = (displayName) => displayName == null
    ? NO_NAME_TO_DISPLAY
    : displayName;

export default checkForNameToDisplay;` in another.

**Comment by JPM709** [comment]
constants in one file, functions in another
