### ISSUE TITLE
Stretch Goal: Finish authorization/authentication

### ISSUE THREAD

**Issue by ecumene** [Hello-World-Software-Studios/calculator#58]
To do this:

- [x] You need to store the JWT somewhere
- [x] The server needs to be able to verify and read user data

**Comment by JPM709** [comment]
jwt stored in local storage for simplicity, however stored in a cookie would be optimal for production build. userID contained in jwt can be decoded at endpoints to query API. jwt included in all API request headers, where authorization mddleware checks validity.
